// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmghabwzgzghigalicdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtZ2hhYnd6Z3pnaGlnYWxpY2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODc1NjgsImV4cCI6MjA3Mzc2MzU2OH0.bcaOcGQa0OD9BzNi5DDC9ANaluaOVgjv52uAPR24xXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});